/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const WageEntry = IDL.Record({
  'percentageSurcharge' : IDL.Opt(IDL.Float64),
  'rate' : IDL.Opt(IDL.Float64),
  'description' : IDL.Text,
  'socialInsuranceFlag' : IDL.Text,
  'taxableBenefitFlag' : IDL.Text,
  'wageTypeCode' : IDL.Text,
  'quantity' : IDL.Opt(IDL.Float64),
  'amount' : IDL.Float64,
  'taxFlag' : IDL.Text,
});
export const Summary = IDL.Record({
  'nettoentgelt' : IDL.Float64,
  'avBeitrag' : IDL.Float64,
  'rvBeitrag' : IDL.Float64,
  'svBrutto' : IDL.Float64,
  'kvBeitrag' : IDL.Float64,
  'pvBeitrag' : IDL.Float64,
  'steuerBrutto' : IDL.Float64,
  'abrechnungsBrutto' : IDL.Float64,
  'auszahlungsbetrag' : IDL.Float64,
});

export const idlService = IDL.Service({
  'addOrUpdateWageEntry' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Opt(IDL.Float64),
        IDL.Opt(IDL.Float64),
        IDL.Opt(IDL.Float64),
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Opt(IDL.Float64),
      ],
      [],
      [],
    ),
  'deleteWageEntry' : IDL.Func([IDL.Text], [], []),
  'getAllWageEntries' : IDL.Func([], [IDL.Vec(WageEntry)], ['query']),
  'getLohnsteuer' : IDL.Func([], [IDL.Float64], ['query']),
  'getSummary' : IDL.Func([], [Summary], ['query']),
  'getWageEntry' : IDL.Func([IDL.Text], [WageEntry], ['query']),
  'setLohnsteuer' : IDL.Func([IDL.Float64], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const WageEntry = IDL.Record({
    'percentageSurcharge' : IDL.Opt(IDL.Float64),
    'rate' : IDL.Opt(IDL.Float64),
    'description' : IDL.Text,
    'socialInsuranceFlag' : IDL.Text,
    'taxableBenefitFlag' : IDL.Text,
    'wageTypeCode' : IDL.Text,
    'quantity' : IDL.Opt(IDL.Float64),
    'amount' : IDL.Float64,
    'taxFlag' : IDL.Text,
  });
  const Summary = IDL.Record({
    'nettoentgelt' : IDL.Float64,
    'avBeitrag' : IDL.Float64,
    'rvBeitrag' : IDL.Float64,
    'svBrutto' : IDL.Float64,
    'kvBeitrag' : IDL.Float64,
    'pvBeitrag' : IDL.Float64,
    'steuerBrutto' : IDL.Float64,
    'abrechnungsBrutto' : IDL.Float64,
    'auszahlungsbetrag' : IDL.Float64,
  });
  
  return IDL.Service({
    'addOrUpdateWageEntry' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Opt(IDL.Float64),
          IDL.Opt(IDL.Float64),
          IDL.Opt(IDL.Float64),
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Opt(IDL.Float64),
        ],
        [],
        [],
      ),
    'deleteWageEntry' : IDL.Func([IDL.Text], [], []),
    'getAllWageEntries' : IDL.Func([], [IDL.Vec(WageEntry)], ['query']),
    'getLohnsteuer' : IDL.Func([], [IDL.Float64], ['query']),
    'getSummary' : IDL.Func([], [Summary], ['query']),
    'getWageEntry' : IDL.Func([IDL.Text], [WageEntry], ['query']),
    'setLohnsteuer' : IDL.Func([IDL.Float64], [], []),
  });
};

export const init = ({ IDL }) => { return []; };