/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Summary {
    nettoentgelt: number;
    avBeitrag: number;
    rvBeitrag: number;
    svBrutto: number;
    kvBeitrag: number;
    pvBeitrag: number;
    steuerBrutto: number;
    abrechnungsBrutto: number;
    auszahlungsbetrag: number;
}
export interface WageEntry {
    percentageSurcharge?: number;
    rate?: number;
    description: string;
    socialInsuranceFlag: string;
    taxableBenefitFlag: string;
    wageTypeCode: string;
    quantity?: number;
    amount: number;
    taxFlag: string;
}
export interface backendInterface {
    addOrUpdateWageEntry(wageTypeCode: string, description: string, quantity: number | null, rate: number | null, percentageSurcharge: number | null, taxFlag: string, socialInsuranceFlag: string, taxableBenefitFlag: string, amount: number | null): Promise<void>;
    deleteWageEntry(wageTypeCode: string): Promise<void>;
    getAllWageEntries(): Promise<Array<WageEntry>>;
    getLohnsteuer(): Promise<number>;
    getSummary(): Promise<Summary>;
    getWageEntry(wageTypeCode: string): Promise<WageEntry>;
    setLohnsteuer(value: number): Promise<void>;
}
import type { WageEntry as _WageEntry } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addOrUpdateWageEntry(arg0: string, arg1: string, arg2: number | null, arg3: number | null, arg4: number | null, arg5: string, arg6: string, arg7: string, arg8: number | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addOrUpdateWageEntry(arg0, arg1, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n1(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n1(this._uploadFile, this._downloadFile, arg4), arg5, arg6, arg7, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg8));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addOrUpdateWageEntry(arg0, arg1, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n1(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n1(this._uploadFile, this._downloadFile, arg4), arg5, arg6, arg7, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg8));
            return result;
        }
    }
    async deleteWageEntry(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteWageEntry(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteWageEntry(arg0);
            return result;
        }
    }
    async getAllWageEntries(): Promise<Array<WageEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllWageEntries();
                return from_candid_vec_n2(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllWageEntries();
            return from_candid_vec_n2(this._uploadFile, this._downloadFile, result);
        }
    }
    async getLohnsteuer(): Promise<number> {
        if (this.processError) {
            try {
                const result = await this.actor.getLohnsteuer();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLohnsteuer();
            return result;
        }
    }
    async getSummary(): Promise<Summary> {
        if (this.processError) {
            try {
                const result = await this.actor.getSummary();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSummary();
            return result;
        }
    }
    async getWageEntry(arg0: string): Promise<WageEntry> {
        if (this.processError) {
            try {
                const result = await this.actor.getWageEntry(arg0);
                return from_candid_WageEntry_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWageEntry(arg0);
            return from_candid_WageEntry_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async setLohnsteuer(arg0: number): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setLohnsteuer(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setLohnsteuer(arg0);
            return result;
        }
    }
}
function from_candid_WageEntry_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _WageEntry): WageEntry {
    return from_candid_record_n4(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [number]): number | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    percentageSurcharge: [] | [number];
    rate: [] | [number];
    description: string;
    socialInsuranceFlag: string;
    taxableBenefitFlag: string;
    wageTypeCode: string;
    quantity: [] | [number];
    amount: number;
    taxFlag: string;
}): {
    percentageSurcharge?: number;
    rate?: number;
    description: string;
    socialInsuranceFlag: string;
    taxableBenefitFlag: string;
    wageTypeCode: string;
    quantity?: number;
    amount: number;
    taxFlag: string;
} {
    return {
        percentageSurcharge: record_opt_to_undefined(from_candid_opt_n5(_uploadFile, _downloadFile, value.percentageSurcharge)),
        rate: record_opt_to_undefined(from_candid_opt_n5(_uploadFile, _downloadFile, value.rate)),
        description: value.description,
        socialInsuranceFlag: value.socialInsuranceFlag,
        taxableBenefitFlag: value.taxableBenefitFlag,
        wageTypeCode: value.wageTypeCode,
        quantity: record_opt_to_undefined(from_candid_opt_n5(_uploadFile, _downloadFile, value.quantity)),
        amount: value.amount,
        taxFlag: value.taxFlag
    };
}
function from_candid_vec_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_WageEntry>): Array<WageEntry> {
    return value.map((x)=>from_candid_WageEntry_n3(_uploadFile, _downloadFile, x));
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: number | null): [] | [number] {
    return value === null ? candid_none() : candid_some(value);
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
