/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Summary {
  'nettoentgelt' : number,
  'avBeitrag' : number,
  'rvBeitrag' : number,
  'svBrutto' : number,
  'kvBeitrag' : number,
  'pvBeitrag' : number,
  'steuerBrutto' : number,
  'abrechnungsBrutto' : number,
  'auszahlungsbetrag' : number,
}
export interface WageEntry {
  'percentageSurcharge' : [] | [number],
  'rate' : [] | [number],
  'description' : string,
  'socialInsuranceFlag' : string,
  'taxableBenefitFlag' : string,
  'wageTypeCode' : string,
  'quantity' : [] | [number],
  'amount' : number,
  'taxFlag' : string,
}
export interface _SERVICE {
  'addOrUpdateWageEntry' : ActorMethod<
    [
      string,
      string,
      [] | [number],
      [] | [number],
      [] | [number],
      string,
      string,
      string,
      [] | [number],
    ],
    undefined
  >,
  'deleteWageEntry' : ActorMethod<[string], undefined>,
  'getAllWageEntries' : ActorMethod<[], Array<WageEntry>>,
  'getLohnsteuer' : ActorMethod<[], number>,
  'getSummary' : ActorMethod<[], Summary>,
  'getWageEntry' : ActorMethod<[string], WageEntry>,
  'setLohnsteuer' : ActorMethod<[number], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];